project:
  type: website

website:
  title: "My Explorations with LLMs"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ekeogh03

format:
  html:
    theme: journal
    css: styles.css

execute:
  freeze: auto


